<?php
/**
 * Created by PhpStorm.
 * User: Simon_
 * Date: 12-12-2017
 * Time: 12:28
 */



$password = "lamePassword";

$hashedPassword = hash('whirlpool',  $password);



$saltedPassword = password_hash($password ,PASSWORD_BCRYPT );
//The salt option has been deprecated as of PHP 7.0.0. It is now preferred to simply use the salt that is generated by default.

//http://php.net/manual/en/function.hash.php




echo "Your password is = " . $password . "<br> hashed password = " . $hashedPassword  . "<br> random salted password = " . $saltedPassword;